### ISSUE TITLE
Can not see the author

### ISSUE THREAD

**Issue by balagab** [mcl-de/redmine_change_issue_author#2]
Hi,

I've installed the plugin, it would be really important for my company, I checked all permission to my admin role (include "Edit issue author), but there is no option to change the issue athor. I tried at a new and existing ticket as well but there is no author field.
Could you please help me?
I use redmine 2.5.0 stable with ms SQLServer, ruby version is  1.9.3-p545, rails version is 3.2.17.

Thanks!

**Comment by Fank** [comment]
Should be fixed with 0.0.2
