### ISSUE TITLE
After installing this plugin (Redmine 2.5.3), it's not possible to change issue Status

### ISSUE THREAD

**Issue by ahlerswebdev** [mcl-de/redmine_change_issue_author#5]
After installing this plugin on Redmine 2.5.3, changing Status from "New" to any other status is no longer possible. Redmine would not allow it.   After removing this plugin, it works again (confirmed).

Andrejs

**Comment by eskin** [comment]
i fixed it in my fork

**Comment by Fank** [comment]
could you please open a pull request?

**Comment by Fank** [comment]
Should be fixed with 0.0.2
